name: gtk-atlantic # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.6.3' # just for humans, typically '1.2+git' or '1.3.2'
summary:  GtkAtlantic is a game like Monopoly(tm).
description: |
   GtkAtlantic is a game like Monopoly(tm). GtkAtlantic is a network client that works with the monopd server.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
icon:  Monopoly_Icon.png
title: GTK Atlantic

apps:
  gtkatlantic:
    command: bin/gtkatlantic
parts:
  gtkatlantic:
    # See 'snapcraft plugins'
    plugin: dump
    source: .
#    build-packages: [default-jre]
#    stage-packages: [default-jre]
    organize:
      gtkatlantic: build/
      gtkatlantic.1: man/man1/

architectures:
  - build-on: amd64

